numpy imported


In [ ]:
#!pip install numpy 

In [2]:
import numpy as np
print("numpy imported")

numpy imported


In [3]:
## Array creation 
ls = [25,14,36,96,85,74,41,52,636,545,55]
arr = np.array(ls)
arr 

array([ 25,  14,  36,  96,  85,  74,  41,  52, 636, 545,  55])

In [4]:
type(arr)
#nd n dimensional array 

numpy.ndarray

In [5]:
ls2 = [25,'upflairs',True,52.36]
ls2 

[25, 'upflairs', True, 52.36]

In [6]:
## Array creation 
ls = [25,14,36,96,85,74,41,52,636,545,55,100.25]
arr = np.array(ls)
arr 

array([ 25.  ,  14.  ,  36.  ,  96.  ,  85.  ,  74.  ,  41.  ,  52.  ,
       636.  , 545.  ,  55.  , 100.25])

In [7]:
## Array creation 
ls = [25,14,36,96,85,74,41,52,636,545,55,'upflairs']
arr = np.array(ls)
arr 

array(['25', '14', '36', '96', '85', '74', '41', '52', '636', '545', '55',
       'upflairs'], dtype='<U11')

In [20]:
## Array creation 
ls = [25,14,36,96,85,74,41,52,636,545,55,251]  ## reverse print 
arr = np.array(ls,)
arr 

array([ 25,  14,  36,  96,  85,  74,  41,  52, 636, 545,  55, 251])

In [11]:
len(arr)

11

In [12]:
arr.size   # or len(arr)

11

In [17]:
# int arr[10] = {1,2,3,45,6,9,85,}; 
arr.dtype

dtype('<U32')

In [23]:
arr[1:] 
# positive and negative 

array([ 14,  36,  96,  85,  74,  41,  52, 636, 545,  55, 251])

In [25]:
np.arange(1,60) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [27]:
import numpy  as np 

In [29]:
arr2= np.arange(60) 
arr2 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [31]:
arr2= np.arange(0,101,2)    # range(starting, stoping , jump )
arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [32]:
len(arr2)

51

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.linspace(1,50,20)   # in between 1 to  50 , item 20

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [40]:
arr = np.random.randint(1,300,500)    # in between 1 - 300 items ==> 500 
arr 

array([125, 249, 185, 166, 277,  35, 100, 203, 237, 151, 289,  32,  48,
        26, 276,  41, 147,  55, 246,  10, 164, 178,  15, 152, 108, 263,
       132, 219, 169, 180, 247, 202, 109, 218, 124,  97, 104,   8, 221,
        78, 203, 103, 127, 155, 138, 279, 138,  31, 135, 196, 171,  78,
        76,  70,  73, 261, 245, 146,  30, 290, 166,  44, 210, 110,  40,
       135,  59, 135, 130, 209, 149, 298, 221, 231, 260, 171, 257, 255,
       218, 276, 257, 289, 253, 124, 104,  78, 150, 246,  32,  29, 246,
       234, 180, 235,  24, 135, 214,  31, 235, 153, 126,   8, 151,  47,
       257,  70,   6, 134,  61,  89, 292, 206,  55, 163,  10, 136, 228,
       181, 254,  25,  26, 293, 155, 154,  69, 165, 198, 215,  95, 178,
       259, 190, 276, 267,  40,  20, 112, 169, 195,  22,   4, 222, 270,
       278, 262, 170, 240, 187, 245, 281,  13, 276, 278, 252, 190, 280,
       146, 153,  19,  61, 136, 231,  68, 195, 183,  83, 131, 177, 171,
       120,  58,  29, 154, 229, 164,  28,  43,   5,  52,  96, 25

In [41]:
arr.size 

500

In [46]:


# filter all items that are less than or equal too   70 
# how many items are present in your array. 

count = 0 
for item in arr:
    if item <=70:
        print(item)
        count = count + 1 

print("No of Item : ",count)

35
32
48
26
41
55
10
15
8
31
70
30
44
40
59
32
29
24
31
8
47
70
6
61
55
10
25
26
69
40
20
22
4
13
19
61
68
58
29
28
43
5
52
22
3
39
34
33
21
4
35
6
50
39
68
38
33
15
58
54
31
64
3
8
5
26
23
65
2
20
49
11
64
70
27
35
55
26
25
3
12
29
19
30
59
20
40
27
34
35
48
5
67
15
56
17
41
12
66
26
65
31
69
18
53
40
25
51
58
41
54
51
60
47
57
No of Item :  115


In [48]:
arr[arr<=70]

array([35, 32, 48, 26, 41, 55, 10, 15,  8, 31, 70, 30, 44, 40, 59, 32, 29,
       24, 31,  8, 47, 70,  6, 61, 55, 10, 25, 26, 69, 40, 20, 22,  4, 13,
       19, 61, 68, 58, 29, 28, 43,  5, 52, 22,  3, 39, 34, 33, 21,  4, 35,
        6, 50, 39, 68, 38, 33, 15, 58, 54, 31, 64,  3,  8,  5, 26, 23, 65,
        2, 20, 49, 11, 64, 70, 27, 35, 55, 26, 25,  3, 12, 29, 19, 30, 59,
       20, 40, 27, 34, 35, 48,  5, 67, 15, 56, 17, 41, 12, 66, 26, 65, 31,
       69, 18, 53, 40, 25, 51, 58, 41, 54, 51, 60, 47, 57])

In [49]:
arr[arr<=70].size


115

In [6]:
arr.ndim 

1

In [8]:
# 2D async
arr 

array([ 25,  14,  36,  96,  85,  74,  41,  52, 636, 545,  55])

In [11]:
#2D [1D,1D,1D,1D]



list

In [10]:
import numpy as np 

In [13]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
type(lst)

list

In [12]:
arr = np.array(lst)
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.shape 
# (row,column)

(3, 3)

In [15]:
arr.ndim    # 

2

In [16]:
arr[2]  # row single

array([7, 8, 9])

In [17]:
arr[0:2]   # multiple row 

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [23]:
arr2 = np.random.randint(1,200,(10,6))
arr2 

array([[132,  89,  15,   4,  17, 186],
       [191, 179,  74, 136, 173,  56],
       [122,  76,  88,  34,  86,  76],
       [ 80, 134,  41, 189,  64,  13],
       [ 58,  91, 167, 116,  47, 142],
       [ 25, 139,  64, 193, 193,  99],
       [ 85,  23,  43, 141,  52,  56],
       [181, 184, 129, 107, 192,  97],
       [180, 106, 164, 145, 176, 149],
       [133, 180, 177, 152, 127, 197]])

In [24]:
arr2[-6:-1,-3:]

array([[116,  47, 142],
       [193, 193,  99],
       [141,  52,  56],
       [107, 192,  97],
       [145, 176, 149]])

In [27]:
arr2[::-1]

array([[133, 180, 177, 152, 127, 197],
       [180, 106, 164, 145, 176, 149],
       [181, 184, 129, 107, 192,  97],
       [ 85,  23,  43, 141,  52,  56],
       [ 25, 139,  64, 193, 193,  99],
       [ 58,  91, 167, 116,  47, 142],
       [ 80, 134,  41, 189,  64,  13],
       [122,  76,  88,  34,  86,  76],
       [191, 179,  74, 136, 173,  56],
       [132,  89,  15,   4,  17, 186]])

In [28]:
arr2 

array([[132,  89,  15,   4,  17, 186],
       [191, 179,  74, 136, 173,  56],
       [122,  76,  88,  34,  86,  76],
       [ 80, 134,  41, 189,  64,  13],
       [ 58,  91, 167, 116,  47, 142],
       [ 25, 139,  64, 193, 193,  99],
       [ 85,  23,  43, 141,  52,  56],
       [181, 184, 129, 107, 192,  97],
       [180, 106, 164, 145, 176, 149],
       [133, 180, 177, 152, 127, 197]])

In [29]:
arr2[-1,-1]

197

In [30]:
arr2[-1,-1]  = 1000

In [31]:
arr2[-1,-1]

1000

In [32]:
arr2 

array([[ 132,   89,   15,    4,   17,  186],
       [ 191,  179,   74,  136,  173,   56],
       [ 122,   76,   88,   34,   86,   76],
       [  80,  134,   41,  189,   64,   13],
       [  58,   91,  167,  116,   47,  142],
       [  25,  139,   64,  193,  193,   99],
       [  85,   23,   43,  141,   52,   56],
       [ 181,  184,  129,  107,  192,   97],
       [ 180,  106,  164,  145,  176,  149],
       [ 133,  180,  177,  152,  127, 1000]])

### comments
dfkdfl ldfjdf ldfjdlfj dfl dl dlkfld 

In [33]:
arr2[0,3]=500

In [34]:
arr2

array([[ 132,   89,   15,  500,   17,  186],
       [ 191,  179,   74,  136,  173,   56],
       [ 122,   76,   88,   34,   86,   76],
       [  80,  134,   41,  189,   64,   13],
       [  58,   91,  167,  116,   47,  142],
       [  25,  139,   64,  193,  193,   99],
       [  85,   23,   43,  141,   52,   56],
       [ 181,  184,  129,  107,  192,   97],
       [ 180,  106,  164,  145,  176,  149],
       [ 133,  180,  177,  152,  127, 1000]])

In [ ]:
arr2[-10,-3] =  500

In [37]:
arr2[0][3]  =  8000

In [38]:
arr2 

array([[ 132,   89,   15, 8000,   17,  186],
       [ 191,  179,   74,  136,  173,   56],
       [ 122,   76,   88,   34,   86,   76],
       [  80,  134,   41,  189,   64,   13],
       [  58,   91,  167,  116,   47,  142],
       [  25,  139,   64,  193,  193,   99],
       [  85,   23,   43,  141,   52,   56],
       [ 181,  184,  129,  107,  192,   97],
       [ 180,  106,  164,  145,  176,  149],
       [ 133,  180,  177,  152,  127, 1000]])

In [1]:
import numpy as np 

In [4]:
# 3D = [2d,2d,2d]

arr3d = np.random.randint(1,200,(5,10,5))
arr3d

array([[[ 34, 103, 181,  70,  45],
        [ 69,  95, 159,  32, 180],
        [131, 194, 131,  31, 188],
        [ 97,  49, 146, 106,  78],
        [181, 178,  29, 146,  93],
        [142, 155,  43, 180,  15],
        [110, 148, 113,  69, 178],
        [161,  97, 173, 131,  83],
        [152,  95, 159,  38, 118],
        [ 58,  53, 121,   4,  40]],

       [[  1, 152, 175, 170,  86],
        [166,  63, 124,  98, 164],
        [185, 110,  99,  89, 122],
        [195,  98, 159, 100, 129],
        [126, 160, 126,  94,  35],
        [  4, 169, 162, 101, 127],
        [ 27,  81,  78,  12,  97],
        [119, 179,  69,  66,  50],
        [ 65, 157, 182, 193, 185],
        [164, 104,   2,  75, 115]],

       [[  5,   9, 169, 173, 132],
        [ 39, 116,  82,  34, 186],
        [149, 132,  37, 189, 115],
        [ 94, 108,  94,  59,  22],
        [149,  22, 165, 183,  55],
        [ 80,   3,  55, 135,  35],
        [184, 133,  85, 177,  89],
        [142, 134,  65, 119, 164],
        [ 25, 14

In [5]:
arr3d.shape 
# (5, 10, 5) 
# 5  ==>  Tables 
# 10 ==>  Rows 
# 5  ==>  columns

(5, 10, 5)

In [6]:
arr3d.ndim 

3

In [12]:
arr3d[0]   # table 

array([[ 34, 103, 181,  70,  45],
       [ 69,  95, 159,  32, 180],
       [131, 194, 131,  31, 188],
       [ 97,  49, 146, 106,  78],
       [181, 178,  29, 146,  93],
       [142, 155,  43, 180,  15],
       [110, 148, 113,  69, 178],
       [161,  97, 173, 131,  83],
       [152,  95, 159,  38, 118],
       [ 58,  53, 121,   4,  40]])

In [13]:
arr3d

array([[[ 34, 103, 181,  70,  45],
        [ 69,  95, 159,  32, 180],
        [131, 194, 131,  31, 188],
        [ 97,  49, 146, 106,  78],
        [181, 178,  29, 146,  93],
        [142, 155,  43, 180,  15],
        [110, 148, 113,  69, 178],
        [161,  97, 173, 131,  83],
        [152,  95, 159,  38, 118],
        [ 58,  53, 121,   4,  40]],

       [[  1, 152, 175, 170,  86],
        [166,  63, 124,  98, 164],
        [185, 110,  99,  89, 122],
        [195,  98, 159, 100, 129],
        [126, 160, 126,  94,  35],
        [  4, 169, 162, 101, 127],
        [ 27,  81,  78,  12,  97],
        [119, 179,  69,  66,  50],
        [ 65, 157, 182, 193, 185],
        [164, 104,   2,  75, 115]],

       [[  5,   9, 169, 173, 132],
        [ 39, 116,  82,  34, 186],
        [149, 132,  37, 189, 115],
        [ 94, 108,  94,  59,  22],
        [149,  22, 165, 183,  55],
        [ 80,   3,  55, 135,  35],
        [184, 133,  85, 177,  89],
        [142, 134,  65, 119, 164],
        [ 25, 14

In [14]:
arr3d[-1,-1,-1]

167

In [17]:
arr = np.arange(60)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [18]:
arr.reshape(20,3)  # 20 , 3 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [21]:
arr2 = arr.reshape(2,15,2)  

In [23]:
arr2.ravel()  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [25]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
arr = np.random.randint(1,200,(5,3))
arr 

array([[ 10,  95,  67],
       [101, 166, 134],
       [ 48,  62, 128],
       [107, 172,  12],
       [112,  65, 194]])

In [27]:
arr.shape 

(5, 3)

In [28]:
np.transpose(arr)

array([[ 10, 101,  48, 107, 112],
       [ 95, 166,  62, 172,  65],
       [ 67, 134, 128,  12, 194]])

In [29]:
np.transpose(arr).shape 

(3, 5)

In [31]:
arr.T 

array([[ 10, 101,  48, 107, 112],
       [ 95, 166,  62, 172,  65],
       [ 67, 134, 128,  12, 194]])

In [33]:
arr2= arr.ravel()
arr2

array([ 10,  95,  67, 101, 166, 134,  48,  62, 128, 107, 172,  12, 112,
        65, 194])

In [38]:
arr2.mean()     #mean()    #max()  #min()

98.2

In [39]:
np.median(arr2)

101.0

In [41]:
arr = np.array([9,7,8])
arr 

array([9, 7, 8])

In [44]:
arr.argmin()

1

In [45]:
arr.argmax()

0

In [46]:
arr 

array([9, 7, 8])

In [47]:
arr.sort()  # ascending order 

In [48]:
arr 

array([7, 8, 9])

In [49]:
arr[::-1]   # descending order 

array([9, 8, 7])

In [50]:
arr = np.array([9,7,8])
arr 

array([9, 7, 8])

In [52]:
arr 

array([9, 7, 8])

In [51]:
arr.argsort()  # [7,8,9] 

array([1, 2, 0], dtype=int64)

In [53]:
import pandas as pd 

<!-- <img src=""> -->

In [ ]:
### 5 july Numpy noteboot upload on linkedin and github